# Generated by Django 6.0.2 on 2026-03-19 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_seed_simulation_capital_v3'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaybillTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_ref', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched'), ('MANUALLY_ASSIGNED', 'Manually Assigned')], default='UNMATCHED', max_length=20)),
                ('match_method', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('contact_attempted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.admins')),
                ('matched_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.loans')),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.users')),
            ],
            options={
                'db_table': 'paybill_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
