# Generated by Django 6.0.2 on 2026-03-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_emaillog_error_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='god_mode_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admins',
            name='god_mode_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='god_mode_grants', to='apps.admins'),
        ),
        migrations.AddField(
            model_name='users',
            name='god_mode_registered',
            field=models.BooleanField(default=False),
        ),
    ]
