# Generated by Django 6.0.2 on 2026-03-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0043_alter_admininvitation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admins',
            name='last_logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admins',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
    ]
