# Generated by Django 6.0.2 on 2026-03-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0044_admins_last_login_at_admins_last_logout_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
    ]
